### ISSUE TITLE
Automate provisioning of tools installed manually

### ISSUE THREAD

**Issue by paulfantom** [thaum-xyz/ankhmorpork#6]
Currently, there are many manually deployed services on NAS. This needs to be adjusted and config should be managed via git.

Discovered services:
- [x] ddclient
- [ ] ~iscsi targetd~ not installed, issue tracked in #2 
- [x] NFS exports

Configuration done on install (may be possible to automate via kickstart):
- [x] ~teamd config for LACP teamed network devices~ done during system installation
- [x] ~mdadm config~ done during installation
- [x] ~LVM config~ done during installation
- [x] ~Static DNS configuration (main DNS server for other clients is running in cluster)~ done during installation
