### ISSUE TITLE
Services to add

### ISSUE THREAD

**Issue by paulfantom** [thaum-xyz/ankhmorpork#9]
- [x] argoCD - ~use following images for multi-arch support: https://hub.docker.com/r/phillebaba/argocd~ custom build images from https://quay.io/repository/paulfantom/argocd
- [x] ~[ZNC IRC bouncer](https://blog.experimental.systems/deploying-znc-in-kubernetes.html)~ moved to riot.im
- [ ] ~calibre-web~
- [ ] ~guacamole, based on [helm chart](https://github.com/prabhatsharma/apache-guacamole-helm-chart)~
- [X] ~[homer](https://github.com/bastienwirtz/homer) or~ [heimdall](https://github.com/linuxserver/Heimdall)
- [x] ~ssh bastion host manager - [bastillion](https://www.bastillion.io/)~ not needed anymore
- [x] ~tekton CI~ no need as github actions used most of the time
- [x] ~keycloak as OIDC backend (needs investigation) or maybe use nextcloud?~
- [x] nextcloud-exporter (added in https://github.com/thaum-xyz/ankhmorpork/pull/24)
- [x] move blog to ghost and host on cluster
- [x] ~add [shynet](https://github.com/milesmcc/shynet) for blog data collection and analysis~ not necessary anymore
- [ ] ~[grafana-operator](https://github.com/integr8ly/grafana-operator)~ grafana in separate namespace
- [x] [unifi-poller](https://github.com/unifi-poller/unifi-poller) instead of current unifi-exporter
- [ ] promtail + loki
- [x] pushgateway at `http://push.monitoring.svc:9091`
- [ ] [photoprism](https://github.com/photoprism/photoprism)

Non-containerized:
- [x] [earlyoom](https://github.com/rfjakob/earlyoom)
